// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4mjqTjlwfkEDqH6loUFj3gRv_ruXzz8',
    appId: '1:652907857052:web:eb8b8e0f7928ed5da95959',
    messagingSenderId: '652907857052',
    projectId: 'anu-coffee',
    authDomain: 'anu-coffee.firebaseapp.com',
    storageBucket: 'anu-coffee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtPCetRQwH2_as1HnJBiBThOl4uxwPhTA',
    appId: '1:652907857052:android:6dd09ba606b95b1ca95959',
    messagingSenderId: '652907857052',
    projectId: 'anu-coffee',
    storageBucket: 'anu-coffee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV4OQx2IRP4S8EZNCrhcK379t5HZD5yG8',
    appId: '1:652907857052:ios:c10a3629fcc15151a95959',
    messagingSenderId: '652907857052',
    projectId: 'anu-coffee',
    storageBucket: 'anu-coffee.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV4OQx2IRP4S8EZNCrhcK379t5HZD5yG8',
    appId: '1:652907857052:ios:c10a3629fcc15151a95959',
    messagingSenderId: '652907857052',
    projectId: 'anu-coffee',
    storageBucket: 'anu-coffee.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj4mjqTjlwfkEDqH6loUFj3gRv_ruXzz8',
    appId: '1:652907857052:web:d442c0b5597adb00a95959',
    messagingSenderId: '652907857052',
    projectId: 'anu-coffee',
    authDomain: 'anu-coffee.firebaseapp.com',
    storageBucket: 'anu-coffee.appspot.com',
  );

}